import type { LedgerState, Project, WeightedScore, WeightCategoryId } from "./types";
import { DEFAULT_SETTINGS, emptyWeighted, LEDGER_VERSION } from "./constants";
import { audit } from "./id";

function scores(
  patch: Partial<Record<WeightCategoryId, Partial<WeightedScore>>>,
): Record<WeightCategoryId, WeightedScore> {
  const base = emptyWeighted();
  for (const [k, v] of Object.entries(patch) as [
    WeightCategoryId,
    Partial<WeightedScore>,
  ][]) {
    base[k] = { ...base[k], ...v };
  }
  return base;
}

const seeded = audit(
  "system",
  "seed",
  "Sample projects loaded for the $1,500 / $2,500 / $4,000 walkthroughs.",
);

const harbor: Project = {
  id: "harbor",
  name: "Harbor Goods site",
  client: "Harbor Goods",
  startDate: "2026-07-01",
  status: "maintenance",
  quotedPrice: 1500,
  invoiceCurrency: "CAD",
  settlementCurrency: "CAD",
  actualReceived: 1500,
  expectedFxRate: null,
  paymentStatus: "paid",
  paymentSchedule: "upfront",
  payments: [
    {
      id: "harbor-p1",
      label: "100% upfront",
      sharePct: 100,
      amount: 1500,
      status: "received",
      receivedAt: "2026-07-03",
      actualReceived: 1500,
    },
  ],
  accountId: "acc-stripe",
  acquisition: "a",
  salesCommissionPct: 10,
  splitMethod: "weighted",
  hybridBase: "weighted",
  fixedSplitA: 50,
  weighted: scores({
    ux: { a: 90, b: 10 },
    ui: { a: 95, b: 5 },
    frontend: { a: 85, b: 15 },
    animations: { a: 100, b: 0 },
    backend: { a: 20, b: 80 },
    api: { a: 10, b: 90 },
    seo: { a: 100, b: 0 },
    deployment: { a: 90, b: 10 },
    sales: { a: 100, b: 0 },
    pm: { a: 90, b: 10 },
  }),
  studioReservePct: 10,
  incomeTaxReservePct: 0,
  gstHstPct: 5,
  taxMode: "inclusive",
  gatewayFeePct: 2.9,
  gatewayFeeFixed: 0.3,
  clientType: "founding",
  originalPrice: 2000,
  discountPct: 25,
  pricingPreset: "starter",
  maintenance: {
    includedMonths: 3,
    startDate: "2026-06-15",
    monthlyAmount: 150,
    currency: "CAD",
    active: true,
  },
  timeEntries: [
    {
      id: "h-t1",
      founder: "a",
      date: "2026-07-08",
      durationRaw: "18h",
      hours: 18,
      role: "frontend",
      note: "Build + motion",
    },
    {
      id: "h-t2",
      founder: "a",
      date: "2026-07-10",
      durationRaw: "10h",
      hours: 10,
      role: "ux",
      note: "UX / UI",
    },
    {
      id: "h-t3",
      founder: "b",
      date: "2026-07-09",
      durationRaw: "8h",
      hours: 8,
      role: "backend",
      note: "Contact form API",
    },
  ],
  expenses: [],
  payouts: [
    {
      id: "h-pay-a",
      founder: "a",
      amount: 400,
      currency: "CAD",
      date: "2026-07-20",
      accountId: "acc-wise",
      note: "First transfer",
    },
  ],
  audit: [seeded],
};

const atlas: Project = {
  id: "atlas",
  name: "Atlas Clinic rebuild",
  client: "Atlas Clinic",
  startDate: "2026-08-04",
  status: "active",
  quotedPrice: 2500,
  invoiceCurrency: "CAD",
  settlementCurrency: "CAD",
  actualReceived: 1250,
  expectedFxRate: null,
  paymentStatus: "partial",
  paymentSchedule: "fifty_fifty",
  payments: [
    {
      id: "atlas-p1",
      label: "50% deposit",
      sharePct: 50,
      amount: 1250,
      status: "received",
      receivedAt: "2026-08-05",
      actualReceived: 1250,
    },
    {
      id: "atlas-p2",
      label: "50% on delivery",
      sharePct: 50,
      amount: 1250,
      status: "pending",
      receivedAt: null,
      actualReceived: null,
    },
  ],
  accountId: "acc-stripe",
  acquisition: "organic",
  salesCommissionPct: 0,
  splitMethod: "hours",
  hybridBase: "hours",
  fixedSplitA: 50,
  weighted: emptyWeighted(),
  studioReservePct: 10,
  incomeTaxReservePct: 0,
  gstHstPct: 5,
  taxMode: "exclusive",
  gatewayFeePct: 2.9,
  gatewayFeeFixed: 0.3,
  clientType: "standard",
  originalPrice: null,
  discountPct: null,
  pricingPreset: "business",
  maintenance: {
    includedMonths: 3,
    startDate: "2026-11-01",
    monthlyAmount: 200,
    currency: "CAD",
    active: false,
  },
  timeEntries: [
    {
      id: "a-t1",
      founder: "a",
      date: "2026-08-10",
      durationRaw: "20h",
      hours: 20,
      role: "frontend",
      note: "",
    },
    {
      id: "a-t2",
      founder: "b",
      date: "2026-08-12",
      durationRaw: "22h",
      hours: 22,
      role: "backend",
      note: "",
    },
  ],
  expenses: [
    {
      id: "a-e1",
      name: "Stripe fee on deposit",
      category: "payment_processing",
      amount: 36.55,
      currency: "CAD",
      paidBy: "studio",
      date: "2026-08-05",
      note: "2.9% + $0.30 on $1,250",
    },
  ],
  payouts: [],
  audit: [seeded],
};

const north: Project = {
  id: "north",
  name: "Northline product site",
  client: "Northline",
  startDate: "2026-06-10",
  status: "delivered",
  quotedPrice: 4000,
  invoiceCurrency: "USD",
  settlementCurrency: "CAD",
  actualReceived: 5320,
  expectedFxRate: 1.36,
  paymentStatus: "paid",
  paymentSchedule: "thirty_seventy",
  payments: [
    {
      id: "n-p1",
      label: "30% deposit",
      sharePct: 30,
      amount: 1200,
      status: "received",
      receivedAt: "2026-06-12",
      actualReceived: 1600,
    },
    {
      id: "n-p2",
      label: "70% launch",
      sharePct: 70,
      amount: 2800,
      status: "received",
      receivedAt: "2026-08-01",
      actualReceived: 3720,
    },
  ],
  accountId: "acc-business",
  acquisition: "a",
  salesCommissionPct: 10,
  splitMethod: "hybrid",
  hybridBase: "weighted",
  fixedSplitA: 55,
  weighted: scores({
    ux: { a: 70, b: 30 },
    ui: { a: 80, b: 20 },
    frontend: { a: 75, b: 25 },
    animations: { a: 100, b: 0 },
    backend: { a: 15, b: 85 },
    api: { a: 10, b: 90 },
    auth: { a: 5, b: 95 },
    integrations: { a: 20, b: 80 },
    seo: { a: 100, b: 0 },
    deployment: { a: 60, b: 40 },
    sales: { a: 100, b: 0 },
    pm: { a: 80, b: 20 },
  }),
  studioReservePct: 10,
  incomeTaxReservePct: 0,
  gstHstPct: 0,
  taxMode: "inclusive",
  gatewayFeePct: 2.9,
  gatewayFeeFixed: 0.3,
  clientType: "standard",
  originalPrice: null,
  discountPct: null,
  pricingPreset: "premium",
  maintenance: {
    includedMonths: 3,
    startDate: "2026-08-01",
    monthlyAmount: 250,
    currency: "CAD",
    active: true,
  },
  timeEntries: [
    {
      id: "n-t1",
      founder: "a",
      date: "2026-06-20",
      durationRaw: "35m",
      hours: 35 / 60,
      role: "pm",
      note: "Kickoff — decimal hours demo",
    },
    {
      id: "n-t2",
      founder: "a",
      date: "2026-07-02",
      durationRaw: "42h",
      hours: 42,
      role: "frontend",
      note: "",
    },
    {
      id: "n-t3",
      founder: "b",
      date: "2026-07-04",
      durationRaw: "38h",
      hours: 38,
      role: "backend",
      note: "",
    },
  ],
  expenses: [
    {
      id: "n-e1",
      name: "Figma Professional",
      category: "software",
      amount: 20,
      currency: "USD",
      paidBy: "a",
      date: "2026-06-15",
      note: "Paid by Founder A — reimburse from studio",
    },
    {
      id: "n-e2",
      name: "Vercel pro (month)",
      category: "hosting",
      amount: 20,
      currency: "USD",
      paidBy: "a",
      date: "2026-07-01",
      note: "",
    },
  ],
  payouts: [
    {
      id: "n-pay-a",
      founder: "a",
      amount: 1200,
      currency: "CAD",
      date: "2026-08-10",
      accountId: "acc-wise",
      note: "Partial CAD transfer",
    },
  ],
  audit: [seeded],
};

export function sampleState(): LedgerState {
  return {
    version: LEDGER_VERSION,
    settings: { ...DEFAULT_SETTINGS },
    accounts: [
      {
        id: "acc-stripe",
        name: "Stripe (CAD)",
        kind: "stripe",
        owner: "studio",
        currency: "CAD",
        notes: "Primary checkout.",
      },
      {
        id: "acc-business",
        name: "Twin V business chequing",
        kind: "business_bank",
        owner: "studio",
        currency: "CAD",
        notes: "",
      },
      {
        id: "acc-personal-a",
        name: "Founder A personal",
        kind: "personal_bank",
        owner: "a",
        currency: "CAD",
        notes: "Do not treat inbound client payments as personal income by default.",
      },
      {
        id: "acc-wise",
        name: "Wise — founder transfers",
        kind: "wise",
        owner: "b",
        currency: "CAD",
        notes: "Cross-border payouts to Founder B.",
      },
    ],
    projects: [harbor, atlas, north],
  };
}
